# Generated by Django 2.0.6 on 2018-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
